### ISSUE TITLE
Module TODO

### ISSUE THREAD

**Issue by quienti** [Lyniven/tomate#10]
## 1. TODO ##

- [x] Create system page
- [x] Create Player
- [x] Create menu
- [x] Create admin system
- [x] Create admin roles
- [x] Create galaxy
- [x] Create planet
- [x] Create system
- [x] Create moon
- [ ] Create building system 
- [ ] Create research 
- [ ] Create ship
- [ ] Create defense 
- [ ] Create fleet action
- [ ] Create messaging 
- [ ] Create league (alliance) 
- [ ] Create support
- [ ] Create friend system 
- [ ] Create Hightscore
- [ ] Create search system
- [ ] Create changelog system
- [ ] Create admin log viewer
- [ ] Create quest system (tutorials, quests and weekly quests)

## 2. Ideas ##

- [x] Add system with planet rotation, like day/night, variable degres (Validated)
- [x] Add new system for ship (custom ship) (Validated)
- [x] Multiple moon (random) (Validated)
- [x] Event: (Validated)
* Meteor
* Solar problem
* Weather on planet

**Comment by quienti** [comment]
Repertory moved in gitlab
